"use client";

import Link from "next/link";
import { useSyncExternalStore } from "react";
import { drillHref, exerciseHref, getDrill, getExercise } from "@/lib/library";
import { activities } from "@/lib/training/templates";
import type { PlanBlock, PlanItem, Prescription } from "@/lib/training/types";
import { localToday } from "@/lib/aft/validation";

const noopSubscribe = () => () => {};

// Today's local date once the browser has hydrated; null during server rendering.
export function useToday(): string | null {
  return useSyncExternalStore(noopSubscribe, localToday, () => null);
}

export function formatPrescription(p: Prescription): string {
  const sets = p.sets && (/^\d+$/.test(p.sets) ? `${p.sets} ${p.sets === "1" ? "set" : "sets"}` : p.sets);
  return [sets, p.reps, p.time, p.rest && `rest ${p.rest}`, p.intensity, p.notes]
    .filter(Boolean)
    .join(" · ");
}

function ItemName({ item }: { item: PlanItem }) {
  if (item.kind === "drill") {
    const drill = getDrill(item.drillId)!;
    return (
      <Link href={drillHref(drill.id)} className="font-medium text-accent hover:underline">
        {drill.name}
      </Link>
    );
  }
  if (item.kind === "exercise") {
    const exercise = getExercise(item.exerciseId)!;
    return (
      <Link href={exerciseHref(exercise.id)} className="font-medium text-accent hover:underline">
        {exercise.name}
      </Link>
    );
  }
  const activity = activities[item.activityId];
  return activity.link ? (
    <Link href={activity.link} className="font-medium text-accent hover:underline">
      {activity.name}
    </Link>
  ) : (
    <span className="font-medium text-ink">{activity.name}</span>
  );
}

export function BlockView({ block, useBuild, condensed }: { block: PlanBlock; useBuild: boolean; condensed?: boolean }) {
  return (
    <li className="rounded-lg border border-line bg-surface-2/40 p-3">
      <div className="flex flex-wrap items-baseline justify-between gap-2">
        <p className="text-sm font-semibold text-ink">{block.title}</p>
        <span className="text-xs text-ink-2">about {block.minutes} min</span>
      </div>
      <ul className="mt-2 space-y-2 text-sm">
        {block.items.map((item, index) => {
          const prescription = useBuild ? item.prescription.build : item.prescription.foundation;
          const skipped =
            item.kind === "drill" && !condensed && item.omit?.length
              ? item.omit.map((id) => getExercise(id)?.name).filter(Boolean).join(", ")
              : "";
          return (
            <li key={index}>
              <ItemName item={item} />
              <p className="text-ink-2">{formatPrescription(prescription)}</p>
              {item.kind === "activity" && <p className="text-xs text-ink-2">{activities[item.activityId].description}</p>}
              {skipped && <p className="text-xs text-ink-2">Skip for your restrictions: {skipped}</p>}
            </li>
          );
        })}
      </ul>
      <details className="mt-2 text-xs text-ink-2">
        <summary className="cursor-pointer hover:text-ink">Sources and assumptions</summary>
        <ul className="mt-1 list-disc space-y-0.5 pl-4">
          {block.sources.map((s) => (
            <li key={s}>{s}</li>
          ))}
          {block.assumptions.map((a) => (
            <li key={a}>RuckOn assumption: {a}</li>
          ))}
        </ul>
      </details>
    </li>
  );
}

export function PlanDisclaimer() {
  return (
    <p className="rounded-lg border border-accent/30 bg-accent/5 px-3 py-2 text-xs text-ink">
      <span className="font-semibold">General suggestion, not an Army-prescribed program.</span> This plan is generated by fixed rules from
      Army drill and training publications and has not been reviewed by a coach or medical professional. It does not replace your
      unit&apos;s H2F program, your provider&apos;s instructions, or a physical profile. Stop and seek advice if you have pain. Plans are
      stored only in this browser.
    </p>
  );
}
